### PR TITLE
fix `mlm:artifact_type` check missing

### LINKED ISSUE #42: Fix missing `mlm:artifact_type` in JSON schema
## :bug: Bug Report

The `mlm:artifact_type` required for the asset representing the model is undefined in the schema.

Because the field is described as "any string", but recommended to be a value matching a framework-specific operation, only a generic `type: string` listing the `examples` should be used.

The property should be added under the `AssetModelRoleMinimumOneDefinition` logic such that it is required for the same asset that contains the `mlm:model` in `roles`. 

The title "Artifact Type Enum" of the section in the README should remove the "Enum" to properly reflect the plain string rather than an explicit enum definition.

Because the 

## :microscope: How To Reproduce

Adding the property should fail any example that is missing it (if any).

### PR DESCRIPTION
**Pull request by fmigneault**
## Description

- Fix missing `mlm:artifact_type` property check for a Model Asset definition.
  The `mlm:artifact_type` is now mutually and exclusively required by the corresponding Asset with `mlm:model` role.
- Fix the examples with the corresponding `mlm:artifact_type` check now enforced.
- Removed "Enum" from "Artifact Type" title since it is not actually an enum.

## Related Issue

- fixes #42

## Type of Change

- [x] :books: Examples, docs, tutorials or dependencies update;
- [x] :wrench: Bug fix (non-breaking change which fixes an issue);
- [ ] :clinking_glasses: Improvement (non-breaking change which improves an existing feature);
- [ ] :rocket: New feature (non-breaking change which adds functionality);
- [ ] :boom: Breaking change (fix or feature that would cause existing functionality to change);
- [ ] :closed_lock_with_key: Security fix.

> [!NOTE]
> "*Potentially*" breaking change if the MLM definition was not formed as described by the README, but not breaking if the worded requirement was applied although unchecked.

## Checklist

- [x] I've read the [`CONTRIBUTING.md`](../CONTRIBUTING.md) guide;
- [x] I've updated the code style using `make check`;
- [x] I've written tests for all new methods and classes that I created;
- [x] I've written the docstring in `Google` format for all the methods and classes that I used.

### CODE REVIEW

**Comment by fmigneault** [comment]
This seems to work correctly when doing item validations via `pystac`. 
However, for some reason, the STAC-node-validator hangs with the referenced schema: 
- https://github.com/stac-utils/stac-node-validator/issues/80

**Comment by m-mohr** [comment]
Commenting here due to the stac-node-validator issue.

I think all of the STAC or STAC extension schemas (except for MLM afaik) are using draft-07. I'd be careful with adding a new schema version to decrease chances of issues. You are facing them with ajv right now in stac-node validator and I'm not sure whether you have checked other validators than pystac? Like in C# or so? I think I'd try to avoid mixing schema versions, especially newer ones for the sake of avoiding potential issues downstream. JSON Schema checks in many places are not really complete anyway (e.g. summaries) so not sure it's that important to use the unevaluatedProperties?

Alternatively, is there a way you can dereference the schema before publishing so that you don't need unevaluatedProperties?

**Comment by fmigneault** [comment]
@m-mohr 
Ideally, I would like to keep draft-07. AFAIK, there's no way to do an `allOf` of multiple schemas with a similar `mlm:` prefix and doing the check of unknown `(?!mlm:)` properties, like every extension does.

If you know a way, please let me know. I've tried for multiple hours, and I cannot find an alternative approach to `unevaluatedProperties` beside manually copy-pasting all fields involved in each `allOf` sub-object into a single one.

**Comment by m-mohr** [comment]
This seems to work:

{89F7F8E6-4FEC-48D7-95E6-7CDAA49E2680}

It needs you to repeat the property names in the patternProperties though, but at least only once as you can also $ref the patternProperties itself in allOf.

But I think I'd just remove the check alltogether if you are not fancy to repeat the values.

**Comment by fmigneault** [comment]
Yeah. Adding the fields in the regex this way is equivalent to duplicating the definition rather than using `allOf` to combine them. Not easily maintainable/scalable with dozens of fields.

**Comment by m-mohr** [comment]
It's not duplicating the schema for the properties though. It's just the names, so comparably short. The same applies partially with the required fields. But yeah, all options are not ideal.

**Comment by fmigneault** [comment]
@m-mohr 
Here's what I have to do to replicate the behavior: https://github.com/stac-extensions/mlm/pull/58/files

**Comment by fmigneault** [comment]
Not really. I would have to copy every field name within the regex, and maintain both regexes with their separate combinations of fields. It makes it harder to read and more prone to errors. At least, schema references are flagged by IDEs if they are invalid.

**Comment by fmigneault** [comment]
Just got an idea worth trying. 
Maybe I can define all possible MLM fields in a single object, and then wrap that in an `allOf` that negates disallowed combination.

```json
{
  "allOf": [
    {"$ref": "#/definitions/all-fields"},
    {"not": {"required": ["mlm:disallowed"]}}
  ],
  "definitions": {
    "all-fields": {
       "properties": {
          "mlm:allowed": {}
       },
       "patternProperties": {
          "^(?!mlm:)": {}
       },
       "additionalProperties": false
    }
  }
}
```

**Pull request merged**
